### ISSUE TITLE
Number of workers can't be changed

### ISSUE THREAD

**Issue by limitlesslab** [Hishiro64/av1an-win-script#22]
[av1an.log.2024-12-10.txt](https://github.com/user-attachments/files/18069912/av1an.log.2024-12-10.txt)
Hi!

Thanks you so much for this great suite of software, but I ran into an issue. No matter the settings I specify, the number of workers stays the same (just 2), regardless of the parameter I specify (for example, 5 workers, just as in the screenshot).

I have an AMD 7940HS processor (8 cores, 16 threads) and, frankly, I used av1an before and I could change the number of workers to whatever I wanted. But not this time and I'm quite baffled as to why it just stays at 2 workers no matter what I do.

How can I solve this?
<img width="736" alt="2024-12-10_083312" src="https://github.com/user-attachments/assets/ef6f4a4c-2f68-47c1-ac71-358d1d4b9ec7">
</div>

**Comment by Hishiro64** [comment]
Total in queue is 2, so the workers will cap out at 2.
From my understanding, since it was fed a short input video, there are more workers than chunks available to work on.
That's why the number of workers didn't match up in your parameters. Input videos you have used before had more or equal chunks to the set worker count.
It should be a nonissue, as it will automatically select the number of workers if it's set to 0.

**Comment by limitlesslab** [comment]
Thank you, you're right. I tried another, longer video, and the workers were set correctly. That's why I closed this issue, lol. 

Anyway, now I know that for very short videos it's just going to be like that and it's normal. I appreciate your response.
