### ISSUE TITLE
Script Not Working, used just the defaults.

### ISSUE THREAD

**Issue by SHREYAN-NANISETTI** [Hishiro64/av1an-win-script#3]
![Av1 Encode ­ƒÉª 04-08-2023 09_54_18](https://github.com/Hishiro64/av1an-win-script/assets/51853987/11bb6930-032d-4d44-ba5c-eea9b0523643)

**Comment by Hishiro64** [comment]
Are you sure the `params.txt` file has not been modified?
The error seems to be pointing to a stray hyphen character in `params.txt`.
Double check the file, you can find a unmodified copy of `params.txt` [here](https://github.com/Hishiro64/av1an-win-script/blob/main/params.txt). Try replacing the file and see if it resolves it.
That is probably the issue here as I wasn't able to reproduce it any other way.

I have tested the script as of today and the defaults do work.
![screen](https://github.com/Hishiro64/av1an-win-script/assets/114261822/baba25f0-83db-485f-a851-07308a06af46)

I don't see any stray hyphen characters in `params.txt` the under the current commit.
The last thing you can try is to clear the contents `params.txt`, as it should also default to working parameters. 

Otherwise, I would need more information.

**Comment by SHREYAN-NANISETTI** [comment]
i got it working by adding " to both sides of output path like this in encode.bat : 
`av1an.exe -i "%%f" -o "./output/output-%%~nf_!queue!.mkv" %args%`

**Comment by SHREYAN-NANISETTI** [comment]
i got it working by adding " to both sides of output path like this in encode.bat : 
`av1an.exe -i "%%f" -o "./output/output-%%~nf_!queue!.mkv" %args%`
